/* tslint:disable */
/* eslint-disable */
/**
 * REST api to TON blockchain explorer
 * Provide access to indexed TON blockchain
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@fslabs.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    AccountAddress,
    AccountAddressFromJSON,
    AccountAddressFromJSONTyped,
    AccountAddressToJSON,
} from './AccountAddress';
import {
    Action,
    ActionFromJSON,
    ActionFromJSONTyped,
    ActionToJSON,
} from './Action';
import {
    Fee,
    FeeFromJSON,
    FeeFromJSONTyped,
    FeeToJSON,
} from './Fee';

/**
 * 
 * @export
 * @interface AccountEvent
 */
export interface AccountEvent {
    /**
     * 
     * @type {string}
     * @memberof AccountEvent
     */
    eventId: string;
    /**
     * 
     * @type {AccountAddress}
     * @memberof AccountEvent
     */
    account: AccountAddress;
    /**
     * 
     * @type {number}
     * @memberof AccountEvent
     */
    timestamp: number;
    /**
     * 
     * @type {Array<Action>}
     * @memberof AccountEvent
     */
    actions: Array<Action>;
    /**
     * 
     * @type {Fee}
     * @memberof AccountEvent
     */
    fee: Fee;
    /**
     * scam
     * @type {boolean}
     * @memberof AccountEvent
     */
    isScam: boolean;
    /**
     * 
     * @type {number}
     * @memberof AccountEvent
     */
    lt: number;
    /**
     * Event is not finished yet. Transactions still happening
     * @type {boolean}
     * @memberof AccountEvent
     */
    inProgress: boolean;
}

export function AccountEventFromJSON(json: any): AccountEvent {
    return AccountEventFromJSONTyped(json, false);
}

export function AccountEventFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountEvent {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'eventId': json['event_id'],
        'account': AccountAddressFromJSON(json['account']),
        'timestamp': json['timestamp'],
        'actions': ((json['actions'] as Array<any>).map(ActionFromJSON)),
        'fee': FeeFromJSON(json['fee']),
        'isScam': json['is_scam'],
        'lt': json['lt'],
        'inProgress': json['in_progress'],
    };
}

export function AccountEventToJSON(value?: AccountEvent | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'event_id': value.eventId,
        'account': AccountAddressToJSON(value.account),
        'timestamp': value.timestamp,
        'actions': ((value.actions as Array<any>).map(ActionToJSON)),
        'fee': FeeToJSON(value.fee),
        'is_scam': value.isScam,
        'lt': value.lt,
        'in_progress': value.inProgress,
    };
}

