/* tslint:disable */
/* eslint-disable */
/**
 * REST api to TON blockchain explorer
 * Provide access to indexed TON blockchain
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@fslabs.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    AccountReprAddress,
    AccountReprAddressFromJSON,
    AccountReprAddressFromJSONTyped,
    AccountReprAddressToJSON,
} from './AccountReprAddress';

/**
 * 
 * @export
 * @interface AccountRepr
 */
export interface AccountRepr {
    /**
     * 
     * @type {number}
     * @memberof AccountRepr
     */
    balance: number;
    /**
     * 
     * @type {string}
     * @memberof AccountRepr
     */
    status: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof AccountRepr
     */
    interfaces: Array<string>;
    /**
     * 
     * @type {AccountReprAddress}
     * @memberof AccountRepr
     */
    address: AccountReprAddress;
    /**
     * 
     * @type {string}
     * @memberof AccountRepr
     */
    name?: string;
    /**
     * 
     * @type {boolean}
     * @memberof AccountRepr
     */
    isScam: boolean;
    /**
     * 
     * @type {string}
     * @memberof AccountRepr
     */
    icon?: string;
    /**
     * 
     * @type {boolean}
     * @memberof AccountRepr
     */
    memoRequired: boolean;
    /**
     * 
     * @type {number}
     * @memberof AccountRepr
     */
    lastUpdate: number;
}

export function AccountReprFromJSON(json: any): AccountRepr {
    return AccountReprFromJSONTyped(json, false);
}

export function AccountReprFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountRepr {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'balance': json['balance'],
        'status': json['status'],
        'interfaces': json['interfaces'],
        'address': AccountReprAddressFromJSON(json['address']),
        'name': !exists(json, 'name') ? undefined : json['name'],
        'isScam': json['is_scam'],
        'icon': !exists(json, 'icon') ? undefined : json['icon'],
        'memoRequired': json['memo_required'],
        'lastUpdate': json['last_update'],
    };
}

export function AccountReprToJSON(value?: AccountRepr | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'balance': value.balance,
        'status': value.status,
        'interfaces': value.interfaces,
        'address': AccountReprAddressToJSON(value.address),
        'name': value.name,
        'is_scam': value.isScam,
        'icon': value.icon,
        'memo_required': value.memoRequired,
        'last_update': value.lastUpdate,
    };
}

