/* tslint:disable */
/* eslint-disable */
/**
 * REST api to TON blockchain explorer
 * Provide access to indexed TON blockchain
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@fslabs.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Annotation,
    AnnotationFromJSON,
    AnnotationFromJSONTyped,
    AnnotationToJSON,
} from './Annotation';

/**
 * 
 * @export
 * @interface Annotations
 */
export interface Annotations {
    /**
     * 
     * @type {Array<Annotation>}
     * @memberof Annotations
     */
    annotations: Array<Annotation>;
}

export function AnnotationsFromJSON(json: any): Annotations {
    return AnnotationsFromJSONTyped(json, false);
}

export function AnnotationsFromJSONTyped(json: any, ignoreDiscriminator: boolean): Annotations {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'annotations': ((json['annotations'] as Array<any>).map(AnnotationFromJSON)),
    };
}

export function AnnotationsToJSON(value?: Annotations | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'annotations': ((value.annotations as Array<any>).map(AnnotationToJSON)),
    };
}

