/* tslint:disable */
/* eslint-disable */
/**
 * REST api to TON blockchain explorer
 * Provide access to indexed TON blockchain
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@fslabs.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Block
 */
export interface Block {
    /**
     * 
     * @type {number}
     * @memberof Block
     */
    seqno: number;
    /**
     * 
     * @type {number}
     * @memberof Block
     */
    workchainId: number;
    /**
     * 
     * @type {string}
     * @memberof Block
     */
    rootHash: string;
    /**
     * 
     * @type {string}
     * @memberof Block
     */
    fileHash: string;
    /**
     * 
     * @type {string}
     * @memberof Block
     */
    shard: string;
    /**
     * 
     * @type {number}
     * @memberof Block
     */
    startLt: number;
    /**
     * 
     * @type {number}
     * @memberof Block
     */
    endLt: number;
}

export function BlockFromJSON(json: any): Block {
    return BlockFromJSONTyped(json, false);
}

export function BlockFromJSONTyped(json: any, ignoreDiscriminator: boolean): Block {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'seqno': json['seqno'],
        'workchainId': json['workchain_id'],
        'rootHash': json['root_hash'],
        'fileHash': json['file_hash'],
        'shard': json['shard'],
        'startLt': json['start_lt'],
        'endLt': json['end_lt'],
    };
}

export function BlockToJSON(value?: Block | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'seqno': value.seqno,
        'workchain_id': value.workchainId,
        'root_hash': value.rootHash,
        'file_hash': value.fileHash,
        'shard': value.shard,
        'start_lt': value.startLt,
        'end_lt': value.endLt,
    };
}

