/* tslint:disable */
/* eslint-disable */
/**
 * REST api to TON blockchain explorer
 * Provide access to indexed TON blockchain
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@fslabs.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    AccountAddress,
    AccountAddressFromJSON,
    AccountAddressFromJSONTyped,
    AccountAddressToJSON,
} from './AccountAddress';

/**
 * 
 * @export
 * @interface DomainInfoNftItem
 */
export interface DomainInfoNftItem {
    /**
     * 
     * @type {string}
     * @memberof DomainInfoNftItem
     */
    address: string;
    /**
     * 
     * @type {AccountAddress}
     * @memberof DomainInfoNftItem
     */
    owner?: AccountAddress;
}

export function DomainInfoNftItemFromJSON(json: any): DomainInfoNftItem {
    return DomainInfoNftItemFromJSONTyped(json, false);
}

export function DomainInfoNftItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): DomainInfoNftItem {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'address': json['address'],
        'owner': !exists(json, 'owner') ? undefined : AccountAddressFromJSON(json['owner']),
    };
}

export function DomainInfoNftItemToJSON(value?: DomainInfoNftItem | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'address': value.address,
        'owner': AccountAddressToJSON(value.owner),
    };
}

