/* tslint:disable */
/* eslint-disable */
/**
 * REST api to TON blockchain explorer
 * Provide access to indexed TON blockchain
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@fslabs.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DomainBid
 */
export interface DomainBid {
    /**
     * 
     * @type {string}
     * @memberof DomainBid
     */
    bidderA: string;
    /**
     * 
     * @type {boolean}
     * @memberof DomainBid
     */
    success: boolean;
    /**
     * 
     * @type {number}
     * @memberof DomainBid
     */
    txTime: number;
    /**
     * 
     * @type {number}
     * @memberof DomainBid
     */
    value: number;
}

/**
 * Check if a given object implements the DomainBid interface.
 */
export function instanceOfDomainBid(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "bidderA" in value;
    isInstance = isInstance && "success" in value;
    isInstance = isInstance && "txTime" in value;
    isInstance = isInstance && "value" in value;

    return isInstance;
}

export function DomainBidFromJSON(json: any): DomainBid {
    return DomainBidFromJSONTyped(json, false);
}

export function DomainBidFromJSONTyped(json: any, ignoreDiscriminator: boolean): DomainBid {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'bidderA': json['bidderA'],
        'success': json['success'],
        'txTime': json['txTime'],
        'value': json['value'],
    };
}

export function DomainBidToJSON(value?: DomainBid | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'bidderA': value.bidderA,
        'success': value.success,
        'txTime': value.txTime,
        'value': value.value,
    };
}

