/* tslint:disable */
/* eslint-disable */
/**
 * REST api to TON blockchain explorer
 * Provide access to indexed TON blockchain
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@fslabs.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface JettonMetadata
 */
export interface JettonMetadata {
    /**
     * 
     * @type {string}
     * @memberof JettonMetadata
     */
    address: string;
    /**
     * 
     * @type {string}
     * @memberof JettonMetadata
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof JettonMetadata
     */
    symbol: string;
    /**
     * 
     * @type {number}
     * @memberof JettonMetadata
     */
    decimals: number;
    /**
     * 
     * @type {string}
     * @memberof JettonMetadata
     */
    image?: string;
    /**
     * 
     * @type {string}
     * @memberof JettonMetadata
     */
    description?: string;
}

export function JettonMetadataFromJSON(json: any): JettonMetadata {
    return JettonMetadataFromJSONTyped(json, false);
}

export function JettonMetadataFromJSONTyped(json: any, ignoreDiscriminator: boolean): JettonMetadata {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'address': json['address'],
        'name': json['name'],
        'symbol': json['symbol'],
        'decimals': json['decimals'],
        'image': !exists(json, 'image') ? undefined : json['image'],
        'description': !exists(json, 'description') ? undefined : json['description'],
    };
}

export function JettonMetadataToJSON(value?: JettonMetadata | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'address': value.address,
        'name': value.name,
        'symbol': value.symbol,
        'decimals': value.decimals,
        'image': value.image,
        'description': value.description,
    };
}

