/* tslint:disable */
/* eslint-disable */
/**
 * REST api to TON blockchain explorer
 * Provide access to indexed TON blockchain
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@fslabs.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AccountAddress } from './AccountAddress';
import {
    AccountAddressFromJSON,
    AccountAddressFromJSONTyped,
    AccountAddressToJSON,
} from './AccountAddress';

/**
 * 
 * @export
 * @interface JettonTransferAction
 */
export interface JettonTransferAction {
    /**
     * amount in quanta of tokens
     * @type {number}
     * @memberof JettonTransferAction
     */
    amount: number;
    /**
     * 
     * @type {string}
     * @memberof JettonTransferAction
     */
    comment?: string;
    /**
     * 
     * @type {object}
     * @memberof JettonTransferAction
     */
    jetton: object;
    /**
     * 
     * @type {AccountAddress}
     * @memberof JettonTransferAction
     */
    recipient: AccountAddress;
    /**
     * 
     * @type {AccountAddress}
     * @memberof JettonTransferAction
     */
    sender: AccountAddress;
}

/**
 * Check if a given object implements the JettonTransferAction interface.
 */
export function instanceOfJettonTransferAction(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "amount" in value;
    isInstance = isInstance && "jetton" in value;
    isInstance = isInstance && "recipient" in value;
    isInstance = isInstance && "sender" in value;

    return isInstance;
}

export function JettonTransferActionFromJSON(json: any): JettonTransferAction {
    return JettonTransferActionFromJSONTyped(json, false);
}

export function JettonTransferActionFromJSONTyped(json: any, ignoreDiscriminator: boolean): JettonTransferAction {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'amount': json['amount'],
        'comment': !exists(json, 'comment') ? undefined : json['comment'],
        'jetton': json['jetton'],
        'recipient': AccountAddressFromJSON(json['recipient']),
        'sender': AccountAddressFromJSON(json['sender']),
    };
}

export function JettonTransferActionToJSON(value?: JettonTransferAction | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'amount': value.amount,
        'comment': value.comment,
        'jetton': value.jetton,
        'recipient': AccountAddressToJSON(value.recipient),
        'sender': AccountAddressToJSON(value.sender),
    };
}

