/* tslint:disable */
/* eslint-disable */
/**
 * REST api to TON blockchain explorer
 * Provide access to indexed TON blockchain
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@fslabs.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    JettonMetadata,
    JettonMetadataFromJSON,
    JettonMetadataFromJSONTyped,
    JettonMetadataToJSON,
} from './JettonMetadata';

/**
 * 
 * @export
 * @interface JettonInfo
 */
export interface JettonInfo {
    /**
     * 
     * @type {boolean}
     * @memberof JettonInfo
     */
    mintable: boolean;
    /**
     * 
     * @type {string}
     * @memberof JettonInfo
     */
    totalSupply: string;
    /**
     * 
     * @type {JettonMetadata}
     * @memberof JettonInfo
     */
    metadata: JettonMetadata;
}

export function JettonInfoFromJSON(json: any): JettonInfo {
    return JettonInfoFromJSONTyped(json, false);
}

export function JettonInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): JettonInfo {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'mintable': json['mintable'],
        'totalSupply': json['total_supply'],
        'metadata': JettonMetadataFromJSON(json['metadata']),
    };
}

export function JettonInfoToJSON(value?: JettonInfo | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'mintable': value.mintable,
        'total_supply': value.totalSupply,
        'metadata': JettonMetadataToJSON(value.metadata),
    };
}

