/* tslint:disable */
/* eslint-disable */
/**
 * REST api to TON blockchain explorer
 * Provide access to indexed TON blockchain
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@fslabs.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    JettonSimpleTransfer,
    JettonSimpleTransferFromJSON,
    JettonSimpleTransferFromJSONTyped,
    JettonSimpleTransferToJSON,
} from './JettonSimpleTransfer';

/**
 * 
 * @export
 * @interface JettonHistory
 */
export interface JettonHistory {
    /**
     * 
     * @type {Array<JettonSimpleTransfer>}
     * @memberof JettonHistory
     */
    history: Array<JettonSimpleTransfer>;
}

export function JettonHistoryFromJSON(json: any): JettonHistory {
    return JettonHistoryFromJSONTyped(json, false);
}

export function JettonHistoryFromJSONTyped(json: any, ignoreDiscriminator: boolean): JettonHistory {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'history': ((json['history'] as Array<any>).map(JettonSimpleTransferFromJSON)),
    };
}

export function JettonHistoryToJSON(value?: JettonHistory | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'history': ((value.history as Array<any>).map(JettonSimpleTransferToJSON)),
    };
}

