/* tslint:disable */
/* eslint-disable */
/**
 * REST api to TON blockchain explorer
 * Provide access to indexed TON blockchain
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@fslabs.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Jetton
 */
export interface Jetton {
    /**
     * 
     * @type {string}
     * @memberof Jetton
     */
    address: string;
    /**
     * 
     * @type {string}
     * @memberof Jetton
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof Jetton
     */
    symbol: string;
    /**
     * 
     * @type {number}
     * @memberof Jetton
     */
    decimals: number;
    /**
     * 
     * @type {string}
     * @memberof Jetton
     */
    image?: string;
}

export function JettonFromJSON(json: any): Jetton {
    return JettonFromJSONTyped(json, false);
}

export function JettonFromJSONTyped(json: any, ignoreDiscriminator: boolean): Jetton {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'address': json['address'],
        'name': json['name'],
        'symbol': json['symbol'],
        'decimals': json['decimals'],
        'image': !exists(json, 'image') ? undefined : json['image'],
    };
}

export function JettonToJSON(value?: Jetton | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'address': value.address,
        'name': value.name,
        'symbol': value.symbol,
        'decimals': value.decimals,
        'image': value.image,
    };
}

