/* tslint:disable */
/* eslint-disable */
/**
 * REST api to TON blockchain explorer
 * Provide access to indexed TON blockchain
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@fslabs.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    AccountAddress,
    AccountAddressFromJSON,
    AccountAddressFromJSONTyped,
    AccountAddressToJSON,
} from './AccountAddress';

/**
 * 
 * @export
 * @interface Message
 */
export interface Message {
    /**
     * 
     * @type {number}
     * @memberof Message
     */
    fwdFee: number;
    /**
     * 
     * @type {number}
     * @memberof Message
     */
    ihrFee: number;
    /**
     * 
     * @type {number}
     * @memberof Message
     */
    createdLt: number;
    /**
     * 
     * @type {number}
     * @memberof Message
     */
    value: number;
    /**
     * 
     * @type {AccountAddress}
     * @memberof Message
     */
    destination?: AccountAddress;
    /**
     * 
     * @type {AccountAddress}
     * @memberof Message
     */
    source?: AccountAddress;
    /**
     * 
     * @type {any}
     * @memberof Message
     */
    msgData: any | null;
}

export function MessageFromJSON(json: any): Message {
    return MessageFromJSONTyped(json, false);
}

export function MessageFromJSONTyped(json: any, ignoreDiscriminator: boolean): Message {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'fwdFee': json['fwd_fee'],
        'ihrFee': json['ihr_fee'],
        'createdLt': json['created_lt'],
        'value': json['value'],
        'destination': !exists(json, 'destination') ? undefined : AccountAddressFromJSON(json['destination']),
        'source': !exists(json, 'source') ? undefined : AccountAddressFromJSON(json['source']),
        'msgData': json['msg_data'],
    };
}

export function MessageToJSON(value?: Message | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'fwd_fee': value.fwdFee,
        'ihr_fee': value.ihrFee,
        'created_lt': value.createdLt,
        'value': value.value,
        'destination': AccountAddressToJSON(value.destination),
        'source': AccountAddressToJSON(value.source),
        'msg_data': value.msgData,
    };
}

