/* tslint:disable */
/* eslint-disable */
/**
 * REST api to TON blockchain explorer
 * Provide access to indexed TON blockchain
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@fslabs.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    NftItem,
    NftItemFromJSON,
    NftItemFromJSONTyped,
    NftItemToJSON,
} from './NftItem';

/**
 * 
 * @export
 * @interface NftItems
 */
export interface NftItems {
    /**
     * 
     * @type {Array<NftItem>}
     * @memberof NftItems
     */
    nftItems: Array<NftItem>;
}

export function NftItemsFromJSON(json: any): NftItems {
    return NftItemsFromJSONTyped(json, false);
}

export function NftItemsFromJSONTyped(json: any, ignoreDiscriminator: boolean): NftItems {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'nftItems': ((json['nft_items'] as Array<any>).map(NftItemFromJSON)),
    };
}

export function NftItemsToJSON(value?: NftItems | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'nft_items': ((value.nftItems as Array<any>).map(NftItemToJSON)),
    };
}

