/* tslint:disable */
/* eslint-disable */
/**
 * REST api to TON blockchain explorer
 * Provide access to indexed TON blockchain
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@fslabs.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    AccountAddress,
    AccountAddressFromJSON,
    AccountAddressFromJSONTyped,
    AccountAddressToJSON,
} from './AccountAddress';
import {
    ImagePreview,
    ImagePreviewFromJSON,
    ImagePreviewFromJSONTyped,
    ImagePreviewToJSON,
} from './ImagePreview';
import {
    NftItemReprCollection,
    NftItemReprCollectionFromJSON,
    NftItemReprCollectionFromJSONTyped,
    NftItemReprCollectionToJSON,
} from './NftItemReprCollection';
import {
    Sale,
    SaleFromJSON,
    SaleFromJSONTyped,
    SaleToJSON,
} from './Sale';

/**
 * 
 * @export
 * @interface NftItemRepr
 */
export interface NftItemRepr {
    /**
     * 
     * @type {string}
     * @memberof NftItemRepr
     */
    address: string;
    /**
     * 
     * @type {number}
     * @memberof NftItemRepr
     */
    index: number;
    /**
     * 
     * @type {AccountAddress}
     * @memberof NftItemRepr
     */
    owner?: AccountAddress;
    /**
     * deprecated
     * @type {string}
     * @memberof NftItemRepr
     * @deprecated
     */
    collectionAddress?: string;
    /**
     * 
     * @type {NftItemReprCollection}
     * @memberof NftItemRepr
     */
    collection?: NftItemReprCollection;
    /**
     * 
     * @type {boolean}
     * @memberof NftItemRepr
     */
    verified: boolean;
    /**
     * 
     * @type {any}
     * @memberof NftItemRepr
     */
    metadata?: any | null;
    /**
     * 
     * @type {Sale}
     * @memberof NftItemRepr
     */
    sale?: Sale;
    /**
     * 
     * @type {Array<ImagePreview>}
     * @memberof NftItemRepr
     */
    previews?: Array<ImagePreview>;
    /**
     * 
     * @type {string}
     * @memberof NftItemRepr
     */
    dns?: string;
}

export function NftItemReprFromJSON(json: any): NftItemRepr {
    return NftItemReprFromJSONTyped(json, false);
}

export function NftItemReprFromJSONTyped(json: any, ignoreDiscriminator: boolean): NftItemRepr {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'address': json['address'],
        'index': json['index'],
        'owner': !exists(json, 'owner') ? undefined : AccountAddressFromJSON(json['owner']),
        'collectionAddress': !exists(json, 'collection_address') ? undefined : json['collection_address'],
        'collection': !exists(json, 'collection') ? undefined : NftItemReprCollectionFromJSON(json['collection']),
        'verified': json['verified'],
        'metadata': !exists(json, 'metadata') ? undefined : json['metadata'],
        'sale': !exists(json, 'sale') ? undefined : SaleFromJSON(json['sale']),
        'previews': !exists(json, 'previews') ? undefined : ((json['previews'] as Array<any>).map(ImagePreviewFromJSON)),
        'dns': !exists(json, 'dns') ? undefined : json['dns'],
    };
}

export function NftItemReprToJSON(value?: NftItemRepr | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'address': value.address,
        'index': value.index,
        'owner': AccountAddressToJSON(value.owner),
        'collection_address': value.collectionAddress,
        'collection': NftItemReprCollectionToJSON(value.collection),
        'verified': value.verified,
        'metadata': value.metadata,
        'sale': SaleToJSON(value.sale),
        'previews': value.previews === undefined ? undefined : ((value.previews as Array<any>).map(ImagePreviewToJSON)),
        'dns': value.dns,
    };
}

