/* tslint:disable */
/* eslint-disable */
/**
 * REST api to TON blockchain explorer
 * Provide access to indexed TON blockchain
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@tonkeeper.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SendMessageRequest
 */
export interface SendMessageRequest {
    /**
     * 
     * @type {string}
     * @memberof SendMessageRequest
     */
    boc?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof SendMessageRequest
     */
    batch?: Array<string>;
}

/**
 * Check if a given object implements the SendMessageRequest interface.
 */
export function instanceOfSendMessageRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function SendMessageRequestFromJSON(json: any): SendMessageRequest {
    return SendMessageRequestFromJSONTyped(json, false);
}

export function SendMessageRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SendMessageRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'boc': !exists(json, 'boc') ? undefined : json['boc'],
        'batch': !exists(json, 'batch') ? undefined : json['batch'],
    };
}

export function SendMessageRequestToJSON(value?: SendMessageRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'boc': value.boc,
        'batch': value.batch,
    };
}

