/* tslint:disable */
/* eslint-disable */
/**
 * REST api to TON blockchain explorer
 * Provide access to indexed TON blockchain
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@tonkeeper.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AccountAddress } from './AccountAddress';
import {
    AccountAddressFromJSON,
    AccountAddressFromJSONTyped,
    AccountAddressToJSON,
} from './AccountAddress';
import type { JettonPreview } from './JettonPreview';
import {
    JettonPreviewFromJSON,
    JettonPreviewFromJSONTyped,
    JettonPreviewToJSON,
} from './JettonPreview';

/**
 * 
 * @export
 * @interface STONfiSwapAction
 */
export interface STONfiSwapAction {
    /**
     * 
     * @type {string}
     * @memberof STONfiSwapAction
     */
    amountIn: string;
    /**
     * 
     * @type {string}
     * @memberof STONfiSwapAction
     */
    amountOut: string;
    /**
     * 
     * @type {AccountAddress}
     * @memberof STONfiSwapAction
     */
    userWallet: AccountAddress;
    /**
     * 
     * @type {AccountAddress}
     * @memberof STONfiSwapAction
     */
    stonfiRouter: AccountAddress;
    /**
     * 
     * @type {string}
     * @memberof STONfiSwapAction
     */
    jettonWalletIn: string;
    /**
     * 
     * @type {JettonPreview}
     * @memberof STONfiSwapAction
     */
    jettonMasterIn: JettonPreview;
    /**
     * 
     * @type {string}
     * @memberof STONfiSwapAction
     */
    jettonWalletOut: string;
    /**
     * 
     * @type {JettonPreview}
     * @memberof STONfiSwapAction
     */
    jettonMasterOut: JettonPreview;
}

/**
 * Check if a given object implements the STONfiSwapAction interface.
 */
export function instanceOfSTONfiSwapAction(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "amountIn" in value;
    isInstance = isInstance && "amountOut" in value;
    isInstance = isInstance && "userWallet" in value;
    isInstance = isInstance && "stonfiRouter" in value;
    isInstance = isInstance && "jettonWalletIn" in value;
    isInstance = isInstance && "jettonMasterIn" in value;
    isInstance = isInstance && "jettonWalletOut" in value;
    isInstance = isInstance && "jettonMasterOut" in value;

    return isInstance;
}

export function STONfiSwapActionFromJSON(json: any): STONfiSwapAction {
    return STONfiSwapActionFromJSONTyped(json, false);
}

export function STONfiSwapActionFromJSONTyped(json: any, ignoreDiscriminator: boolean): STONfiSwapAction {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'amountIn': json['amount_in'],
        'amountOut': json['amount_out'],
        'userWallet': AccountAddressFromJSON(json['user_wallet']),
        'stonfiRouter': AccountAddressFromJSON(json['stonfi_router']),
        'jettonWalletIn': json['jetton_wallet_in'],
        'jettonMasterIn': JettonPreviewFromJSON(json['jetton_master_in']),
        'jettonWalletOut': json['jetton_wallet_out'],
        'jettonMasterOut': JettonPreviewFromJSON(json['jetton_master_out']),
    };
}

export function STONfiSwapActionToJSON(value?: STONfiSwapAction | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'amount_in': value.amountIn,
        'amount_out': value.amountOut,
        'user_wallet': AccountAddressToJSON(value.userWallet),
        'stonfi_router': AccountAddressToJSON(value.stonfiRouter),
        'jetton_wallet_in': value.jettonWalletIn,
        'jetton_master_in': JettonPreviewToJSON(value.jettonMasterIn),
        'jetton_wallet_out': value.jettonWalletOut,
        'jetton_master_out': JettonPreviewToJSON(value.jettonMasterOut),
    };
}

