/* tslint:disable */
/* eslint-disable */
/**
 * REST api to TON blockchain explorer
 * Provide access to indexed TON blockchain
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@fslabs.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    AccountAddress,
    AccountAddressFromJSON,
    AccountAddressFromJSONTyped,
    AccountAddressToJSON,
} from './AccountAddress';

/**
 * 
 * @export
 * @interface TonTransferAction
 */
export interface TonTransferAction {
    /**
     * 
     * @type {AccountAddress}
     * @memberof TonTransferAction
     */
    sender: AccountAddress;
    /**
     * 
     * @type {AccountAddress}
     * @memberof TonTransferAction
     */
    recipient: AccountAddress;
    /**
     * amount in nanotons
     * @type {number}
     * @memberof TonTransferAction
     */
    amount: number;
    /**
     * 
     * @type {string}
     * @memberof TonTransferAction
     */
    comment?: string;
    /**
     * raw hex encoded payload
     * @type {string}
     * @memberof TonTransferAction
     */
    payload?: string;
}

export function TonTransferActionFromJSON(json: any): TonTransferAction {
    return TonTransferActionFromJSONTyped(json, false);
}

export function TonTransferActionFromJSONTyped(json: any, ignoreDiscriminator: boolean): TonTransferAction {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'sender': AccountAddressFromJSON(json['sender']),
        'recipient': AccountAddressFromJSON(json['recipient']),
        'amount': json['amount'],
        'comment': !exists(json, 'comment') ? undefined : json['comment'],
        'payload': !exists(json, 'payload') ? undefined : json['payload'],
    };
}

export function TonTransferActionToJSON(value?: TonTransferAction | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'sender': AccountAddressToJSON(value.sender),
        'recipient': AccountAddressToJSON(value.recipient),
        'amount': value.amount,
        'comment': value.comment,
        'payload': value.payload,
    };
}

