/* tslint:disable */
/* eslint-disable */
/**
 * REST api to TON blockchain explorer
 * Provide access to indexed TON blockchain
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@fslabs.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    AccountAddress,
    AccountAddressFromJSON,
    AccountAddressFromJSONTyped,
    AccountAddressToJSON,
} from './AccountAddress';
import {
    TraceTX,
    TraceTXFromJSON,
    TraceTXFromJSONTyped,
    TraceTXToJSON,
} from './TraceTX';

/**
 * 
 * @export
 * @interface TraceMsg
 */
export interface TraceMsg {
    /**
     * 
     * @type {number}
     * @memberof TraceMsg
     */
    fwdFee: number;
    /**
     * 
     * @type {number}
     * @memberof TraceMsg
     */
    ihrFee: number;
    /**
     * 
     * @type {number}
     * @memberof TraceMsg
     */
    createdLt: number;
    /**
     * 
     * @type {number}
     * @memberof TraceMsg
     */
    value: number;
    /**
     * 
     * @type {AccountAddress}
     * @memberof TraceMsg
     */
    destination: AccountAddress;
    /**
     * 
     * @type {AccountAddress}
     * @memberof TraceMsg
     */
    source: AccountAddress;
    /**
     * 
     * @type {string}
     * @memberof TraceMsg
     */
    comment?: string;
    /**
     * 
     * @type {TraceTX}
     * @memberof TraceMsg
     */
    tx?: TraceTX;
}

export function TraceMsgFromJSON(json: any): TraceMsg {
    return TraceMsgFromJSONTyped(json, false);
}

export function TraceMsgFromJSONTyped(json: any, ignoreDiscriminator: boolean): TraceMsg {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'fwdFee': json['fwd_fee'],
        'ihrFee': json['ihr_fee'],
        'createdLt': json['created_lt'],
        'value': json['value'],
        'destination': AccountAddressFromJSON(json['destination']),
        'source': AccountAddressFromJSON(json['source']),
        'comment': !exists(json, 'comment') ? undefined : json['comment'],
        'tx': !exists(json, 'tx') ? undefined : TraceTXFromJSON(json['tx']),
    };
}

export function TraceMsgToJSON(value?: TraceMsg | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'fwd_fee': value.fwdFee,
        'ihr_fee': value.ihrFee,
        'created_lt': value.createdLt,
        'value': value.value,
        'destination': AccountAddressToJSON(value.destination),
        'source': AccountAddressToJSON(value.source),
        'comment': value.comment,
        'tx': TraceTXToJSON(value.tx),
    };
}

